@URL = https://railwaycoman-production.up.railway.app

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "pablo",
    "apellido": "nbavas",
    "provincia": "Buenos Aires"
}


###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario/1



###
# Crear usuario
POST {{URL}}/dieta
Content-Type: application/json

{
    "id_dieta": 1,
    "nombre": "Dieta del caballo",
    "descripcion": "paja y agua",
    "filtro_carbohidratos": "muchos",
    "filtro_proteina": "1000g de proteina",
    "filtro_condicion": "caballo",

}